name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"
    #runs-on: "self-hosted"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t nilsbolle/aiapi:20240312 .

    - name: Log in to Docker Hub (optional)
      if: success()
      run: docker login -u ${{ secrets.DOCKERHUB_USERNAME2 }} -p ${{ secrets.DOCKERHUB_PASSWORD2 }}

    - name: Push Docker image to Docker Hub (optional)
      if: success()
      run: docker push nilsbolle/aiapi:20240312